#!/bin/bash -xe
# Clear the old docker.pid on restart
rm -rf /var/run/docker.pid
sleep 3s

# Start docker daemon
dockerd &

# Wait a little bit for the daemon
sleep 3s

# Remove unused containers, images and networks
docker system prune -f

# Start services and clean orphaned containers
docker-compose -f dind-compose.yml up --remove-orphans

# Sleep forever is things fail
while true; do sleep 10000; done
